site_name: Ros2_control
nav:
  - Introducci칩n e instalaci칩n: index.md
  - Los paquetes de ros2_control: ros2control.md
  - Conceptos b치sicos de ros2_control: conceptos_basicos.md
  - Interfaz hardware: hardware.md
  - Creaci칩n de un controlador propio: controlador_propio.md
theme:
  features:
    - content.code.select
    - content.code.copy
  name: material

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js